load(
    "@sedgealgos-cpp//bazel:sedgealgos_build_system.bzl",
    "sedgealgos_cc_library",
    "sedgealgos_cc_test",
)

sedgealgos_cc_library(
    name = "stopwatch",
    hdrs = ["stopwatch.hpp"],
    srcs = ["stopwatch.cpp"],
)

