load(
    "@sedgealgos-cpp//bazel:sedgealgos_build_system.bzl",
    "sedgealgos_cc_library",
    "sedgealgos_cc_test",
)

sedgealgos_cc_library(
    name = "merge_sort",
    hdrs = [
        "merge_sort.hpp",
    ],
    deps = [
        "//sedgealgos/algorithms/sort/sort:callbacks",
    ]
)