load(
    "@sedgealgos-cpp//bazel:sedgealgos_build_system.bzl",
    "sedgealgos_cc_library",
    "sedgealgos_cc_test_library"
)

sedgealgos_cc_library(
    name = "callbacks",
    hdrs = [
        "callbacks.hpp",
    ],
)

sedgealgos_cc_library(
    name = "is_sorted",
    hdrs = [
        "is_sorted.hpp",
    ],
)

sedgealgos_cc_test_library(
    name = "callbacks_mock",
    hdrs = [
        "callbacks_mock.hpp",
    ]
)