load(
    "@sedgealgos-cpp//bazel:sedgealgos_build_system.bzl",
    "sedgealgos_cc_library",
)

sedgealgos_cc_library(
    name = "merge",
    hdrs = [
        "merge.hpp",
    ],
    deps = [
        "//sedgealgos/algorithms/sort/sort:callbacks",
    ],
)

sedgealgos_cc_library(
    name = "faster_merge",
    hdrs = [
        "faster_merge.hpp",
    ],
    deps = [
        "//sedgealgos/algorithms/sort/sort:callbacks",        
    ]
)

sedgealgos_cc_library(
    name = "no_copy_merge",
    hdrs = [
        "no_copy_merge.hpp",
    ],
    deps = [
        "//sedgealgos/algorithms/sort/sort:callbacks",        
    ]
)