load(
    "@sedgealgos-cpp//bazel:sedgealgos_build_system.bzl",
    "sedgealgos_cc_library",
)

sedgealgos_cc_library(
    name = "merge",
    hdrs = [
        "merge.hpp",
    ],
    deps = [
        "//sedgealgos/algorithms/sort/sort:callbacks",
    ],
)